run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  misspell:
    locale: US
