name: Feature Request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Remember: paw is a personal tool. The best approach is often to fork and add features yourself.
        That said, if you think a feature would benefit the core tool, describe it here.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about.
